### ISSUE TITLE
### Display best test results for each difficulty level (could-have)

### ISSUE THREAD

**Issue by Carlos-n21** [Carlos-n21/Type-Racer#15]
**User story**

As a competitive user, I want my best results for each difficulty level to be displayed so that I can compare my progress.

**Acceptance Criteria:**

- [x] The best test result for each level is stored
- [x] The best test result for each level is displayed on the site

**Tasks:**

- [x] Create an area to display the best test results for each level of difficulty
- [x] The best test result for each level is stored and displayed to the user
